<?php

namespace ContainerPsCWfhH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLogParserService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\LogParser' shared autowired service.
     *
     * @return \App\Service\LogParser
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/LogParser.php';

        return $container->privates['App\\Service\\LogParser'] = new \App\Service\LogParser();
    }
}
