<?php

namespace ContainerPsCWfhH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getParseLogCommandService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Command\ParseLogCommand' shared autowired service.
     *
     * @return \App\Command\ParseLogCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/ParseLogCommand.php';
        include_once \dirname(__DIR__, 4).'/src/Service/LogParser.php';

        $container->privates['App\\Command\\ParseLogCommand'] = $instance = new \App\Command\ParseLogCommand(($container->privates['App\\Service\\LogParser'] ?? ($container->privates['App\\Service\\LogParser'] = new \App\Service\LogParser())), ($container->privates['parameter_bag'] ?? ($container->privates['parameter_bag'] = new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container))), ($container->services['doctrine'] ?? $container->getDoctrineService()));

        $instance->setName('app:parse-log');
        $instance->setAliases([0 => 'app:parse']);
        $instance->setDescription('parse log file');

        return $instance;
    }
}
