<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_healthcheck_index' => [[], ['_controller' => 'App\\Controller\\HealthCheckController::index'], [], [['text', '/healthz']], [], [], []],
    'app_log_index' => [[], ['_controller' => 'App\\Controller\\LogController::index'], [], [['text', '/count']], [], [], []],
];
